version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: info.log
    encoding: utf8

  error_file_handler:
    class: logging.FileHandler
    level: ERROR
    formatter: standard
    filename: errors.log
    encoding: utf8

loggers:
  debug_logger:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler]
    propagate: no

root:
  level: INFO
  handlers: [info_file_handler, error_file_handler]
  propagate: yes